# Generated by Django 6.0.7 on 2026-07-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcash_model',
            name='datetime',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense_model',
            name='datetime',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
